version: "3"

services:

  mysql:

    image: mysql:8

    volumes:

      - .db:/var/lib/mysql/data

    environment:

      MYSQL_DB: keycloak


      MYSQL_ROOT_PASSWORD: root

  keycloak:

    image: quay.io/keycloak/keycloak:18.0.2

    command:

      - start-dev --log-console-color true

    environment:

      KC_DB_VENDOR: MYSQL

      KC_DB_ADDR: mysql

      KC_DB_DATABASE: keycloak

      KC_DB_USERNAME: keycloak

      KC_DB_SCHEMA: public

      KC_DB_PASSWORD: root

      KEYCLOAK_ADMIN: admin

      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HOSTNAME: localhost

      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.

      #JDBC_PARAMS: "ssl=true"

    ports:

      - 8081:8080

    depends_on:

      - mysql




volumes:

  mysql_data:

    driver: local